var buttonNum = 0;
$(document).ready(function(){
    $("#addButton").click(function(){
      //$("#addButton").removeClass("bttnIsActive");
      buttonNum = 1;
      $(this).toggleClass("bttnIsActive");
      $("#subButton").removeClass("bttnIsActive");
      $("#scalarMult").removeClass("bttnIsActive");
      $("#dotProd").removeClass("bttnIsActive");
      $("#crossProd").removeClass("bttnIsActive");
      $("#scalarContain").hide();
      $("#optionContain").css({"display": "-webkit-flex", "display": "flex", "justify-content": "center", "align-items": "center", "flex-direction": "-webkit-column", "flex-direction": "column"});
      $("#wContain").css({"display": "block"});
      $("#submitButton").show();
      $("#vAddW").show();
      $("#vSubW").hide();
      $("#scalMultResult").hide();
      $("#vDotW").hide();
      $("#crossProdResult").hide();
    });
    $("#subButton").click(function(){
      //$("#subButton").removeClass("bttnIsActive");
      buttonNum = 2;
      $(this).toggleClass("bttnIsActive");
      $("#addButton").removeClass("bttnIsActive");
      $("#scalarMult").removeClass("bttnIsActive");
      $("#dotProd").removeClass("bttnIsActive");
      $("#crossProd").removeClass("bttnIsActive");
      $("#scalarContain").hide();
      $("#optionContain").css({"display": "-webkit-flex", "display": "flex", "justify-content": "center", "align-items": "center", "flex-direction": "-webkit-column", "flex-direction": "column"});
      $("#wContain").css({"display": "block"});
      $("#submitButton").show();
      $("#vAddW").hide();
      $("#vSubW").show();
      $("#scalMultResult").hide();
      $("#vDotW").hide();
      $("#crossProdResult").hide();
    });
    $("#scalarMult").click(function(){
      //$("#scalarMult").removeClass("bttnIsActive");
      buttonNum = 3;
      $(this).toggleClass("bttnIsActive"); 
      $("#addButton").removeClass("bttnIsActive");
      $("#subButton").removeClass("bttnIsActive");
      $("#dotProd").removeClass("bttnIsActive");
      $("#crossProd").removeClass("bttnIsActive");
      $("#wContain").hide();
      $("#optionContain").css({"display": "-webkit-flex", "display": "flex", "justify-content": "center", "align-items": "center", "flex-direction": "-webkit-column", "flex-direction": "column"});
      $("#scalarContain").css({"display": "block"});
      $("#submitButton").show();
      $("#vAddW").hide();
      $("#vSubW").hide();
      $("#scalMultResult").show();
      $("#vDotW").hide();
      $("#crossProdResult").hide();
    });
    $("#dotProd").click(function(){
      //$("#dotProd").removeClass("bttnIsActive");
      buttonNum = 4;
      $(this).toggleClass("bttnIsActive"); 
      $("#addButton").removeClass("bttnIsActive");
      $("#scalarMult").removeClass("bttnIsActive");
      $("#subButton").removeClass("bttnIsActive");
      $("#crossProd").removeClass("bttnIsActive");
      $("#scalarContain").hide();
      $("#optionContain").css({"display": "-webkit-flex", "display": "flex", "justify-content": "center", "align-items": "center", "flex-direction": "-webkit-column", "flex-direction": "column"});
      $("#wContain").css({"display": "block"});
      $("#submitButton").show();
      $("#vAddW").hide();
      $("#vSubW").hide();
      $("#scalMultResult").hide();
      $("#vDotW").show();
      $("#crossProdResult").hide();
    });
    $("#crossProd").click(function(){
      //$("#crossProd").removeClass("bttnIsActive");
      buttonNum = 5;
      $(this).toggleClass("bttnIsActive"); 
      $("#addButton").removeClass("bttnIsActive");
      $("#scalarMult").removeClass("bttnIsActive");
      $("#dotProd").removeClass("bttnIsActive");
      $("#subButton").removeClass("bttnIsActive");
      $("#scalarContain").hide();
      $("#optionContain").css({"display": "-webkit-flex", "display": "flex", "justify-content": "center", "align-items": "center", "flex-direction": "-webkit-column", "flex-direction": "column"});
      $("#wContain").css({"display": "block"});
      $("#submitButton").show();
      $("#vAddW").hide();
      $("#vSubW").hide();
      $("#scalMultResult").hide();
      $("#vDotW").hide();
      $("#crossProdResult").show();
    });
});